//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Twice.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        internal static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active mutes.
        /// </summary>
        internal static string ActiveMutes {
            get {
                return ResourceManager.GetString("ActiveMutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active until.
        /// </summary>
        internal static string ActiveUntil {
            get {
                return ResourceManager.GetString("ActiveUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added favorite.
        /// </summary>
        internal static string AddedFavorite {
            get {
                return ResourceManager.GetString("AddedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago.
        /// </summary>
        internal static string Ago {
            get {
                return ResourceManager.GetString("Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available notification mechanisms.
        /// </summary>
        internal static string AvailableNotificationMechanisms {
            get {
                return ResourceManager.GetString("AvailableNotificationMechanisms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked user.
        /// </summary>
        internal static string BlockedUser {
            get {
                return ResourceManager.GetString("BlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built on.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the selected filter?.
        /// </summary>
        internal static string ConfirmDeleteFilter {
            get {
                return ResourceManager.GetString("ConfirmDeleteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tweet.
        /// </summary>
        internal static string CopyTweet {
            get {
                return ResourceManager.GetString("CopyTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tweet URL.
        /// </summary>
        internal static string CopyTweetUrl {
            get {
                return ResourceManager.GetString("CopyTweetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        internal static string CopyUrl {
            get {
                return ResourceManager.GetString("CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        internal static string Corner_BottomLeft {
            get {
                return ResourceManager.GetString("Corner_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        internal static string Corner_BottomRight {
            get {
                return ResourceManager.GetString("Corner_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        internal static string Corner_TopLeft {
            get {
                return ResourceManager.GetString("Corner_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        internal static string Corner_TopRight {
            get {
                return ResourceManager.GetString("Corner_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner to show popups in.
        /// </summary>
        internal static string CornerToShowPopupsIn {
            get {
                return ResourceManager.GetString("CornerToShowPopupsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must not be in the past.
        /// </summary>
        internal static string DastMustNotBeInThePast {
            get {
                return ResourceManager.GetString("DastMustNotBeInThePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string DaysShort {
            get {
                return ResourceManager.GetString("DaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display to show popups at.
        /// </summary>
        internal static string DisplayToShowPopupsAt {
            get {
                return ResourceManager.GetString("DisplayToShowPopupsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no accounts added. Do you want to add one right now?.
        /// </summary>
        internal static string DoYouWantToAddANewAccount {
            get {
                return ResourceManager.GetString("DoYouWantToAddANewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed tweet.
        /// </summary>
        internal static string EmbedTweet {
            get {
                return ResourceManager.GetString("EmbedTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorited {0} times.
        /// </summary>
        internal static string FavoritedXTimes {
            get {
                return ResourceManager.GetString("FavoritedXTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite tweet.
        /// </summary>
        internal static string FavoriteTweet {
            get {
                return ResourceManager.GetString("FavoriteTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourites.
        /// </summary>
        internal static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter criteria.
        /// </summary>
        internal static string FilterCriteria {
            get {
                return ResourceManager.GetString("FilterCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Follow {
            get {
                return ResourceManager.GetString("Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        internal static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge.
        /// </summary>
        internal static string FontSize_Huge {
            get {
                return ResourceManager.GetString("FontSize_Huge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string FontSize_Large {
            get {
                return ResourceManager.GetString("FontSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FontSize_Normal {
            get {
                return ResourceManager.GetString("FontSize_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string FontSize_Small {
            get {
                return ResourceManager.GetString("FontSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny.
        /// </summary>
        internal static string FontSize_Tiny {
            get {
                return ResourceManager.GetString("FontSize_Tiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forever.
        /// </summary>
        internal static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of hashtags.
        /// </summary>
        internal static string HashtagColor {
            get {
                return ResourceManager.GetString("HashtagColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inline media in timelines.
        /// </summary>
        internal static string InlineMediaInTimeline {
            get {
                return ResourceManager.GetString("InlineMediaInTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default account.
        /// </summary>
        internal static string IsDefaultAccount {
            get {
                return ResourceManager.GetString("IsDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of links.
        /// </summary>
        internal static string LinkColor {
            get {
                return ResourceManager.GetString("LinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage columns.
        /// </summary>
        internal static string ManageColumns {
            get {
                return ResourceManager.GetString("ManageColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of user mentions.
        /// </summary>
        internal static string MentionColor {
            get {
                return ResourceManager.GetString("MentionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions.
        /// </summary>
        internal static string Mentions {
            get {
                return ResourceManager.GetString("Mentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mentions of an account.
        /// </summary>
        internal static string MentionsDescription {
            get {
                return ResourceManager.GetString("MentionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages sent from/to an account.
        /// </summary>
        internal static string MessagesDescription {
            get {
                return ResourceManager.GetString("MessagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute hashtag.
        /// </summary>
        internal static string MuteHashtag {
            get {
                return ResourceManager.GetString("MuteHashtag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute user.
        /// </summary>
        internal static string MuteUser {
            get {
                return ResourceManager.GetString("MuteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muting.
        /// </summary>
        internal static string Muting {
            get {
                return ResourceManager.GetString("Muting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name already exists.
        /// </summary>
        internal static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose tweet.
        /// </summary>
        internal static string NewTweet {
            get {
                return ResourceManager.GetString("NewTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account added.
        /// </summary>
        internal static string NoAccountAdded {
            get {
                return ResourceManager.GetString("NoAccountAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no further settings for this type of notifications.
        /// </summary>
        internal static string NoFurtherSettingsForThisNotificationType {
            get {
                return ResourceManager.GetString("NoFurtherSettingsForThisNotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification popups.
        /// </summary>
        internal static string PopupNotification {
            get {
                return ResourceManager.GetString("PopupNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary color.
        /// </summary>
        internal static string PrimaryColor {
            get {
                return ResourceManager.GetString("PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed favorite.
        /// </summary>
        internal static string RemovedFavorite {
            get {
                return ResourceManager.GetString("RemovedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply all.
        /// </summary>
        internal static string ReplyAll {
            get {
                return ResourceManager.GetString("ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report spam.
        /// </summary>
        internal static string ReportSpam {
            get {
                return ResourceManager.GetString("ReportSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweet.
        /// </summary>
        internal static string Retweet {
            get {
                return ResourceManager.GetString("Retweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweeted status.
        /// </summary>
        internal static string RetweetedStatus {
            get {
                return ResourceManager.GetString("RetweetedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retweeted {0} times.
        /// </summary>
        internal static string RetweetedXTimes {
            get {
                return ResourceManager.GetString("RetweetedXTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a value.
        /// </summary>
        internal static string SelectAValue {
            get {
                return ResourceManager.GetString("SelectAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share tweet.
        /// </summary>
        internal static string ShareTweet {
            get {
                return ResourceManager.GetString("ShareTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show separator between statuses.
        /// </summary>
        internal static string ShowStatusSeparator {
            get {
                return ResourceManager.GetString("ShowStatusSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound file.
        /// </summary>
        internal static string SoundFile {
            get {
                return ResourceManager.GetString("SoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sounds.
        /// </summary>
        internal static string SoundNotification {
            get {
                return ResourceManager.GetString("SoundNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted status.
        /// </summary>
        internal static string StatusDeleted {
            get {
                return ResourceManager.GetString("StatusDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the timeline of an account.
        /// </summary>
        internal static string TimelineDescription {
            get {
                return ResourceManager.GetString("TimelineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification toasts in app.
        /// </summary>
        internal static string ToastNotification {
            get {
                return ResourceManager.GetString("ToastNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate tweet.
        /// </summary>
        internal static string TranslateTweet {
            get {
                return ResourceManager.GetString("TranslateTweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweets.
        /// </summary>
        internal static string Tweets {
            get {
                return ResourceManager.GetString("Tweets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the PIN that is displayed on the website after authorizing Twice to access your twitter account.
        /// </summary>
        internal static string TwitterPinEntry {
            get {
                return ResourceManager.GetString("TwitterPinEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfollow.
        /// </summary>
        internal static string Unfollow {
            get {
                return ResourceManager.GetString("Unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tweets of a user.
        /// </summary>
        internal static string UserDescription {
            get {
                return ResourceManager.GetString("UserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} retweeted.
        /// </summary>
        internal static string UserRetweeted {
            get {
                return ResourceManager.GetString("UserRetweeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must not be empty.
        /// </summary>
        internal static string ValueMustNotBeEmpty {
            get {
                return ResourceManager.GetString("ValueMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via.
        /// </summary>
        internal static string Via {
            get {
                return ResourceManager.GetString("Via", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
